/* Isolated localhost browser QA, no wallet, no user browser/profile. */
const { chromium } = require("playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
(async()=>{
 const base=process.env.TEST_URL||"http://127.0.0.1:8790",out=path.resolve("test-results");
 await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,channel:"chrome"});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:"light"});
  const page=await context.newPage(),errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  const response=await context.request.get(base+"/api/mints/flows");
  assert.equal(response.status(),200);
  const data=await response.json();
  assert.equal(data.ready,true,JSON.stringify(data.status));
  assert.equal(data.snapshot.ledger_verified,true);
  assert.equal(data.timezone,"Asia/Nicosia");
  const s=data.summary;
  assert.equal(BigInt(s.pooled_raw)+BigInt(s.outside_raw)+BigInt(s.burned_raw),BigInt(s.minted_raw));
  assert(data.sales.every(e=>e.kind==="sell"&&e.quote_asset==="USDT"));
  await page.goto(base);
  await page.locator("#mint-chart .chart-line").waitFor();
  await page.locator("#sales-chart .chart-line").waitFor();
  await page.locator("#flow-content").waitFor({state:"visible"});
  assert.equal(await page.locator("#flow-sold").getAttribute("title"),await page.evaluate(raw=>GonkaChart.exact(raw,9),s.sold_raw)+" WGNK");
  assert.equal(await page.evaluate(()=>clock(Date.parse("2026-01-01T21:30:00Z")/1000)),"23:30:00");
  assert.equal(await page.evaluate(()=>date(Date.parse("2026-01-01T21:30:00Z")/1000)),"01.01.2026");
  assert.equal(await page.evaluate(()=>date(Date.parse("2026-07-01T21:30:00Z")/1000)),"02.07.2026");
  assert.doesNotMatch(await page.locator("body").innerText(),/Кипр/i);
  const svg=page.locator("#mint-chart svg");
  await svg.scrollIntoViewIfNeeded();
  await svg.focus();await svg.press("Home");
  assert.equal(await page.locator("#mint-chart .chart-tooltip").isVisible(),true);
  assert.doesNotMatch(await page.locator("#mint-chart .chart-tooltip").innerText(),/Кипр/i);
  await page.locator(".chart-panel").screenshot({path:path.join(out,"cyprus-mint-chart-light.png")});
  await page.getByRole("button",{name:"Столбцы",exact:true}).click();
  assert(await page.locator("#mint-chart .chart-bar").count()>0);
  await page.getByRole("button",{name:"График",exact:true}).click();
  assert.equal(await page.locator("#mint-chart .chart-line").count(),1);
  await page.locator(".distribution-panel").screenshot({path:path.join(out,"wgnk-distribution.png")});
  await page.getByRole("button",{name:"Цена",exact:true}).click();
  assert.equal(await page.locator("#sales-chart-title").innerText(),"Средняя цена продаж · все адреса");
  const priceChart=page.locator("#sales-chart svg");
  await priceChart.focus();await priceChart.press("End");
  assert.match(await page.locator("#sales-chart .chart-tooltip").innerText(),/USDT \/ WGNK/);
  await page.locator(".sales-chart-panel").screenshot({path:path.join(out,"wgnk-sale-prices.png")});
  await page.getByRole("button",{name:"Объём",exact:true}).click();
  await page.locator(".sales-chart-panel").screenshot({path:path.join(out,"wgnk-sale-volume.png")});
  await page.locator("#sales-next").click();
  await page.waitForFunction(()=>document.getElementById("sales-page").textContent.startsWith("26"));
  await page.locator("#sales-prev").click();
  await page.waitForFunction(()=>document.getElementById("sales-page").textContent.startsWith("1–"));
  await page.locator('[data-view="minters"]').click();
  assert.equal(await page.locator("#minter-rows tr").count(),data.minters.length);
  const first=data.minters[0].address;
  await page.locator('#minter-rows [data-flow-address="'+first+'"]').click();
  await page.waitForResponse(r=>r.url().includes("/api/mints/flows?")&&new URL(r.url()).searchParams.get("q")===first);
  assert.equal(await page.locator("#sales-query").inputValue(),first);
  await page.locator("#sales-reset").click();
  await page.waitForResponse(r=>r.url().includes("/api/mints/flows?")&&new URL(r.url()).searchParams.get("q")==="");
  await page.locator("#sales-period").selectOption("24");
  await page.waitForResponse(r=>r.url().includes("/api/mints/flows?")&&new URL(r.url()).searchParams.get("hours")==="24");
  await page.locator("#sales-reset").click();
  await page.waitForResponse(r=>r.url().includes("/api/mints/flows?")&&new URL(r.url()).searchParams.get("hours")==="0");
  await page.getByRole("button",{name:"Светлая тема",exact:true}).click();
  await page.locator(".distribution-panel").screenshot({path:path.join(out,"wgnk-distribution-dark.png")});
  await page.locator(".chart-panel").screenshot({path:path.join(out,"cyprus-mint-chart-dark.png")});
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>document.querySelector("#mint-chart svg").viewBox.baseVal.width<390);
  const width=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth}));
  assert(width.body<=width.viewport,JSON.stringify(width));
  await page.locator(".chart-panel").screenshot({path:path.join(out,"cyprus-mint-chart-mobile.png")});
  await page.locator(".distribution-panel").screenshot({path:path.join(out,"wgnk-distribution-mobile.png")});
  await page.locator(".sales-chart-panel").screenshot({path:path.join(out,"wgnk-sales-mobile.png")});
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,errors,width,snapshot:data.snapshot.height,pooled:s.pooled,sold:s.sold,average_price:s.average_price,
    checks:["Cyprus winter/summer","distribution reconciliation","mint line/bar","keyboard tooltip","sales volume/price","pagination","minter filter","period","light/dark","mobile"],screenshots:out}));
  await context.close();
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
