/* Headless-only local UI regression check. Does not control any user browser. */
const { chromium } = require("playwright");
const fs = require("node:fs/promises");
const path = require("node:path");
const assert = require("node:assert/strict");
(async()=>{
 const browser = await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:1440,height:1040}});
 const errors=[];page.on("pageerror",e=>errors.push(e.message));
 const base=process.env.TEST_URL||"http://127.0.0.1:8790";
 const out=path.resolve("test-results");await fs.mkdir(out,{recursive:true});
 await page.goto(base);
 await page.locator("#price").filter({hasNotText:"—"}).waitFor({timeout:30000});
 await page.screenshot({path:path.join(out,"desktop.png"),fullPage:true});
 await page.getByRole("button",{name:"⇄ Поток транзакций",exact:true}).click();
 await page.getByRole("button",{name:"Сделки",exact:true}).click();
 await page.waitForResponse(r=>r.url().includes("/api/events?")&&r.status()===200);
 assert(await page.locator("#activity-body").innerText());
 await page.getByRole("button",{name:"⤨ Мост GNK ↔ WGNK",exact:true}).click();
 await page.locator(".bridge-card").first().waitFor({timeout:30000});
 await page.screenshot({path:path.join(out,"bridge.png"),fullPage:false});
 await page.getByRole("button",{name:"▥ Хосты и награды",exact:true}).click();
 await page.locator("#hosts-body tr").first().waitFor();
 await page.getByRole("textbox",{name:"Фильтр хостов"}).fill("no-such-host");
 await page.getByText("Хостов по этому фильтру не найдено.").waitFor();
 await page.getByRole("textbox",{name:"Фильтр хостов"}).fill("");
 await page.getByRole("textbox",{name:"Найти кошелёк"}).fill("0x972a7a92d92796a98801a8818bcf91f1648f2f68");
 await page.getByRole("button",{name:"Найти адрес",exact:true}).click();
 await page.getByRole("button",{name:"Копировать адрес"}).waitFor({timeout:30000});
 await page.getByRole("button",{name:"Закрыть",exact:true}).click();
 await page.getByRole("button",{name:"◎ Источники и метод",exact:true}).click();
 await page.getByText("Точность и хранение",{exact:true}).waitFor();
 await page.getByRole("button",{name:"◫ Обзор ↗",exact:true}).click();
 await page.getByRole("button",{name:"LIVE",exact:true}).click();
 await page.getByRole("button",{name:"ПАУЗА",exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,"mobile.png"),fullPage:true});
 const width=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth}));
 assert(width.body<=width.viewport+1,JSON.stringify(width));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({ok:true,errors,viewport:width,screenshots:out},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
